#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/vortex/Desktop/Krimskrams/Tests/Te$
export DISPLAY=:0.0
cd /home/vortex/Desktop/Krimskrams/Tests/Testrepo
command git pull;
command git add --all;
command git commit -m "auto commit";
command git push;
echo "done" > "done.txt"
